replicas: 1


image: 119266638796.dkr.ecr.us-west-2.amazonaws.com/payment-and-withdraw
version: c6567a98

labels: {}
annotations: {} 

resources:
  limits:
    cpu: 700m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 1Gi

affinity: {}
nodeSelector: {}

readinessProbe:
  httpGet:
    path: /monitor/health
    port: http

startupProbe:
  httpGet:
    path: /monitor/health
    port: http
  failureThreshold: 10
  periodSeconds: 3 

livenessProbe:
  httpGet:
    path: /monitor/health
    port: http

enviroments:
    # Default environments, this variables can be override on the "values" definition
  defaults: {}
    # non sensitive variables
  values: {}
    # sensitive variables
  secrets: {}

service:
    type: ClusterIP
    loadBalancerIP: 
    port: 7006
    
    labels: {} 
    annotations: {}  

namespace:
  # Create namespace
  create: false
  labels: {}
  annotations: {}  

registry:
  servers:
  - name: payment-and-withdraw
    server: 119266638796.dkr.ecr.us-west-2.amazonaws.com/payment-and-withdraw
    username: 
    password: 
    releasename: md-pay-draw-1637369573




