apiVersion: v1
kind: Secret
metadata:
  labels:  
    {{- include "common.helm" . | nindent 4 }}  
  namespace: {{ include "md-pay-draw.namespace" . }}
  name: {{ include "common.name.value" . }}
data:
  {{- if .Values.enviroments.secrets }}
    {{- range $key, $value := .Values.enviroments.secrets }}
    {{- $key | nindent 2 }}: {{ $value | b64enc }}
    {{- end }}
  {{- end }}