apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:  
    {{- include "common.helm" . | nindent 4 }}  
    {{- include "md-pay-draw.service.label" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.name.value" . }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
  selector:
    {{- include "md-pay-draw.label" . | nindent 4 }}
