{{- if .Values.servers }}
{{- range .Values.servers }}
{{- if and .server .username .password }}
apiVersion: v1
kind: Secret
metadata:
  labels:  
    {{- include "common.helm" $ | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
  name: {{ .name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "common.registry.secret" (dict "server" .server "username" .username "password" .password) | quote }}
{{- end }}  
{{- end }}  
{{- end }}